### ISSUE TITLE
Can't get text objects to work

### ISSUE THREAD

**Issue by jasonlong** [stephenway/vim-textobj-css#1]
Wow, this is exactly the `vim-textobj` plugin I've been looking for. For some reason, this is my only textobj addon that doesn't seem to work. Hitting `vac` for example, doesn't do anything. Is there something I can do to try to debug this? 

Really hoping to get this working!

**Comment by stephenway** [comment]
Hey, sorry about that, just restructured a bit and now it works again. You'll want to delete this project out of your `~/.vim/bundles/` then re-clone or install.

**Comment by jasonlong** [comment]
Great, thank you good sir!

As someone who has put more thought into this, quick question for you if you don't mind: Do you know of a similar text object technique that would allow you to do something like this...

```sass
// Where * is the cursor
.awesome-sauce {
  .margin-top: 10px;
  
  &.spicy {
    pad*ing: 10px;
  }
}
```

... and you could select the entire `&.spicy` block? And performing it again would select the entire `.awesome-sauce` block? Regular paragraph text objects can handle vanilla CSS blocks, but nesting and empty lines trip it up.

**Comment by stephenway** [comment]
Yea that's what I think was breaking the basic functionality, definitely useful and something I plan on adding back in because I'm nesting with PostCSS and it would be infinitely helpful. PR is welcome of course. :smile:

**Comment by jasonlong** [comment]
Ah ok, so you already had this in mind here. I don't have any experience hacking on vim-textobj plugins, but I may try to take a look because I'd really love this functionality.

Anyhow, thanks again!

**Comment by stephenway** [comment]
@jasonlong  Just figured out you can utilize paragraphs for manipulating nested selectors like `vip` or `vap`. Just use `d` or `y` instead if needed.

**Comment by jasonlong** [comment]
In my experience, paragraph text objects have never worked right here. They seem to only consider blank lines as boundaries. For example, `vip` with the cursor in `margin-top` in the example above would only select that line and the one above it. I'd like a text object that could grab the entire block in that scenario. Or if you were in the `.spicy` block, it would select that section and hitting `ac` (or whatever) again would select the entire parent block.

**Comment by jasonlong** [comment]
Meant to include how `vat` for tag text objects is super handy in that you can select a block and continue hitting `at` to continue selecting entire parent blocks up the DOM. I'm basically after the same thing for CSS/Sass/etc.

**Comment by jasonlong** [comment]
I've got a basic plugin working over at https://github.com/jasonlong/vim-textobj-css. No docs or anything yet, but it uses `ac`/`ic` if you want to try it (though you'd have to disable your plugin temporarily since they use the same keys.
